ALTER TABLE lawyers
ADD COLUMN IF NOT EXISTS address VARCHAR(255);

ALTER TABLE lawyers
ADD COLUMN IF NOT EXISTS area VARCHAR(150);

ALTER TABLE lawyers
ADD COLUMN IF NOT EXISTS mobile VARCHAR(60);

ALTER TABLE courts
ADD COLUMN IF NOT EXISTS address VARCHAR(255);

ALTER TABLE courts
ADD COLUMN IF NOT EXISTS area VARCHAR(150);
