CREATE TABLE IF NOT EXISTS user_login_company_codes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  user_key VARCHAR(200) NOT NULL UNIQUE,
  company_code VARCHAR(40) NOT NULL,
  last_used_at TIMESTAMP DEFAULT NOW(),
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

