BEGIN;

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  done BOOLEAN NOT NULL DEFAULT FALSE,
  todo_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by INTEGER,
  assigned_to INTEGER,
  done_by INTEGER,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

ALTER TABLE todos
  ADD COLUMN IF NOT EXISTS todo_date DATE;
ALTER TABLE todos
  ALTER COLUMN todo_date SET DEFAULT CURRENT_DATE;
UPDATE todos
SET todo_date = COALESCE(todo_date, DATE("createdAt"), CURRENT_DATE)
WHERE todo_date IS NULL;
ALTER TABLE todos
  ALTER COLUMN todo_date SET NOT NULL;

ALTER TABLE todos
  ADD COLUMN IF NOT EXISTS done BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE todos
  ADD COLUMN IF NOT EXISTS created_by INTEGER;
ALTER TABLE todos
  ADD COLUMN IF NOT EXISTS assigned_to INTEGER;
ALTER TABLE todos
  ADD COLUMN IF NOT EXISTS done_by INTEGER;

CREATE INDEX IF NOT EXISTS todos_todo_date_idx ON todos(todo_date);
CREATE INDEX IF NOT EXISTS todos_assigned_to_idx ON todos(assigned_to);

COMMIT;
