ALTER TABLE cases
ADD COLUMN IF NOT EXISTS case_step VARCHAR(20);

ALTER TABLE cases
DROP CONSTRAINT IF EXISTS cases_case_step_check;

UPDATE cases
SET case_step = 'STEP'
WHERE case_step IS NULL OR TRIM(case_step) = '';

UPDATE cases
SET case_step = CASE
  WHEN UPPER(REPLACE(TRIM(case_step), ' ', '_')) IN ('NEXT_STEP', 'NEXTSTEP', 'PLAINT_STEP', 'PLAINTSTEP') THEN 'PLAINT_STEP'
  WHEN UPPER(REPLACE(TRIM(case_step), ' ', '_')) IN ('ANSWER_STEP', 'ANSWERSTEP') THEN 'ANSWER_STEP'
  WHEN UPPER(REPLACE(TRIM(case_step), ' ', '_')) IN ('LW_STEP', 'LWSTEP', 'L_W_STEP') THEN 'LW_STEP'
  WHEN UPPER(REPLACE(TRIM(case_step), ' ', '_')) IN ('DUDGMENT_STEP', 'DUDGMENTSTEP', 'JUDGMENT_STEP', 'JUDGMENTSTEP') THEN 'DUDGMENT_STEP'
  ELSE 'STEP'
END;

ALTER TABLE cases
ALTER COLUMN case_step SET DEFAULT 'STEP';

ALTER TABLE cases
ALTER COLUMN case_step SET NOT NULL;

ALTER TABLE cases
ADD CONSTRAINT cases_case_step_check
CHECK (case_step IN ('STEP', 'PLAINT_STEP', 'ANSWER_STEP', 'LW_STEP', 'DUDGMENT_STEP'));

CREATE INDEX IF NOT EXISTS cases_case_step_idx ON cases(case_step);
