ALTER TABLE plaints
ADD COLUMN IF NOT EXISTS edit_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE answers
ADD COLUMN IF NOT EXISTS edit_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE witnesses
ADD COLUMN IF NOT EXISTS upload_method VARCHAR(50);

ALTER TABLE witnesses
ADD COLUMN IF NOT EXISTS uploads_json JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE witnesses
ADD COLUMN IF NOT EXISTS edit_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE judgments
ADD COLUMN IF NOT EXISTS edit_enabled BOOLEAN NOT NULL DEFAULT FALSE;
